name: CI/CD for Wisecow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate TLS certificates
        run: |
          openssl req -x509 -newkey rsa:2048 -nodes -keyout tls/wisecow.key -out tls/wisecow.crt -days 365 -subj "/C=US/ST=State/L=Locality/O=Organization/CN=wisecow.example.com"
      - name: Build and push image
        run: |
          docker build -t wisecow:latest.
          docker push wisecow:latest
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          kubernetes_config: ${{ secrets.KUBECONFIG }}
          image_name: wisecow:latest
          manifest: deployment.yaml
          tls_secret: wisecow-tls
